title: Jess Chen's Personal Website
description: PhD Candidate | AI Researcher

theme: minima

# author:
#   name: "Jess Chen"

header_pages:
  - projects.md
  - publications.md
  - blog.md
  - cv.md
  - contact.md