title: Jess Chen's Personal Website
description: PhD Candidate | AI Researcher

theme: minima

# author:
#   name: "Jess Chen"

extra_css:
  - style.scss

header_pages:
  - projects.md
  - publications.md
  - blog.md
  - cv.md
  - contact.md